images:
- path: spec/components/properties/image
  kind: Application
nameReference:
- kind: ConfigMap
  fieldSpecs:
  - kind: Application
    path: spec/components/properties/env/valueFrom/configMapKeyRef/name